/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "README",
    {
      type: "category",
      label: "课程说明",
      link: {
        type: "generated-index",
        description: "一点点课程相关的介绍，对学习 Linux 本身并没有任何帮助",
      },
      items: [{ type: "autogenerated", dirName: "pre" }],
    },
    {
      type: "category",
      label: "主要章节",
      items: [{ type: "autogenerated", dirName: "main" }],
      link: {
        type: "generated-index",
        description:
          "接下来就是开始 Linux 正式的学习了，相信看完这些章节，你一定会收获颇丰！",
      },
      collapsed: false,
    },
    {
      type: "category",
      label: "附加章节",
      items: [{ type: "autogenerated", dirName: "ex" }],
      link: {
        type: "generated-index",
        description:
          "这些是没有在 Linux 学习主路线上的章节内容，只是单纯的章节分类，事实上与主章一样重要！",
      },
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
